---
# tasks file for ansible-role-jira

- name: "Create jira group :: {{ jira_user }}"
  group:
    name: "{{ jira_group }}"

- name: "Create jira user :: {{ jira_group }}"
  user:
    name: "{{ jira_user }}"
    group: "{{ jira_group }}"
    home: "{{ jira_home }}"

- name: "Download & extract Jira {{ jira_archive }}"
  unarchive:
    src: "{{ jira_download_url }}"
    dest: "{{ jira_work_dir }}/{{ jira_version }"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0755
    copy: no
    creates: "{{ jira_work_dir }}/atlassian-jira-{{ jira_version }}"

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ jira_templates }}"
